language: go
sudo: false

go:
- 1.7

script:
- ./codecov.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -ko ./swaggerui.zip "https://github.com/swagger-api/swagger-ui/archive/v2.2.5.zip")

install:
before_deploy:
  - GOOS=linux GOARCH=amd64 go build -o xparse_linux_amd64
  - GOOS=linux GOARCH=386 go build -o xparse_linux_386
  - GOOS=linux GOARCH=arm go build -o xparse_linux_arm
  - GOOS=darwin GOARCH=amd64 go build -o xparse_darwin_amd64
  - GOOS=windows GOARCH=amd64 go build -o xparse_windows_amd64.exe
  - GOOS=windows GOARCH=386 go build -o xparse_windows_386.exe

deploy:
  skip_cleanup: true
  overwrite: true
  provider: releases
  file:
    - xparse_linux_amd64
    - xparse_linux_386
    - xparse_linux_arm
    - xparse_darwin_amd64
    - xparse_windows_amd64.exe
    - xparse_windows_386.exe
  on:
    tags: true
    repo: itsbalamurali/parse-server
